import { Injectable } from "@angular/core";

import { SmartHttpClient } from '@core/services';
import { TemplateModel } from '@editor/models';
import { map, Observable, of } from "rxjs";

import * as appHelpers from './editor.helpers';
import { AppConfig } from '@shared/services';

@Injectable({
    providedIn: 'root'
})
export class TemplatesService {

    constructor(private http: SmartHttpClient) { }

    getTemplate(path: string): Observable<TemplateModel> {

        // todo: must be generated by config rules
        // todo: for urls must be separated service

        const url = `${AppConfig.templateUrl}&path=${path}`;
        return this.http.get<TemplateModel>(url);
    }

    saveTemplate(templates: { [filepath: string]: TemplateModel }): Observable<any> {
        const files = JSON.stringify(templates);
        return this.http.post(AppConfig.saveTemplates, { files });
    }
}
