import { Injectable } from "@angular/core";

import { BuilderHttpClient, AppConfig } from '@integration/services';
import { TemplateModel } from '@models/document';
import { map, Observable, of } from "rxjs";

// import { helpers } from '@editor/helpers';
import { TemplateEntry } from '@shared/models';
import {  } from '@integration/services';

@Injectable({
    providedIn: 'root'
})
export class TemplatesService {

    constructor(private http: BuilderHttpClient, private appConfig: AppConfig) { }

    getTemplate(template: TemplateEntry): Observable<TemplateModel | null> {

        // todo: must be generated by config rules
        // todo: for urls must be separated service

        if (!template.path) {
            return of(null);
        }

        const templateUrl = this.appConfig.getValue('templateUrl');
        const url = `${templateUrl}&path=${template.path}&type=${template.type}`;
        return this.http.get<TemplateModel>(url);
    }

    saveTemplate(templates: { path: string, type: string, content: TemplateModel }[]): Observable<any> {
        const files = JSON.stringify(templates);
        const saveTemplates = this.appConfig.getValue('saveTemplates');
        // todo: note that it probably should be using doRequest method
        return this.http.post(saveTemplates, { files });
    }
}
